
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: blogproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
  


# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python manage.py migrate
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DEBUG=True  # Set your Django settings here

#   # PostgreSQL Database
#   db:
#     image: postgres # You can use a different PostgreSQL version
#     environment:
#       POSTGRES_DB: blogproject
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: psql
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
