version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=blogproject.settings
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blogproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
